version: '3'

services:
  db:
    image: tobi312/rpi-mariadb:10.11-debian-20230716053240.23db75ef
    container_name: anyshell-db
    restart: always
    ports:
      - '<dbPort>:3306'
    volumes:
      - /opt/anyshell-server/db-config:/etc/mysql/conf.d
      - /opt/anyshell-server/db-data:/var/lib/mysql
      - /opt/anyshell-server/sql:/opt/sql
    environment:
      MYSQL_ROOT_PASSWORD: <rootPassword>

  ssh:
    container_name: anyshell-ssh
    restart: always
    ports:
      - '<sshPort>:22'
    build: 
      context: ./ssh
      args:
        password: <userPassword>

  web:
    container_name: anyshell-web
    image: phpmyadmin
    restart: always
    ports:
      - '<webPort>:80'
    environment:
      PMA_HOST: db
